import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ApolloWrapper } from "~/providers/apollo-provider";
import { ModalProvider } from "~/components/ui/modal/modal-context";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <ApolloWrapper>
          <ModalProvider>{children}</ModalProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
